ALTER TABLE `ddv_diseases` ADD COLUMN `Id` VARCHAR(32) NULL  AFTER `PID`;
ALTER TABLE `ddv_diseases_vaccines` ADD COLUMN `Id` VARCHAR(32) NULL  AFTER `PID`;
ALTER TABLE `ddv_dosageoptions` ADD COLUMN `Id` VARCHAR(32) NULL  AFTER `PID`;
ALTER TABLE `ddv_ssidrugs` ADD COLUMN `Id` VARCHAR(32) NULL  AFTER `PID`;
ALTER TABLE `ddv_vaccinationplanitems` ADD COLUMN `Id` VARCHAR(32) NULL  AFTER `PID`;
ALTER TABLE `ddv_vaccinationplans` ADD COLUMN `Id` VARCHAR(32) NULL  AFTER `PID`;
ALTER TABLE `ddv_vaccines` ADD COLUMN `Id` VARCHAR(32) NULL  AFTER `PID`;
ALTER TABLE `ddv_vaccinesdrugs` ADD COLUMN `Id` VARCHAR(32) NULL  AFTER `PID`;